#!/usr/bin/env python

from subprocess import Popen, PIPE
import re
import sys
from exceptions import UnicodeDecodeError

sys.stdin = open('/dev/tty')


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


SUSPICIOUS_FILENAME_EXTENSIONS = (
    'rsa', 'dsa', '.private_key', '.psql_history', '.mysql_history',
    '.pem', '.log', '.htpasswd', '.key', 'tblk',
)

SUSPICIOUS_FILENAME_KEYWORDS = (
    'opvn', 'keychain', 'password', 'backup', 'tblk', 'credentials',
)

SUSPICIOUS_CREDENTIALS = set(
    [re.compile(regex, flags=re.IGNORECASE) for regex in [
        '[\w]{40}', # aws secret key
        '.*PRIVATE KEY.*', # rsa, ssl keys
        '.*password.*', # literal 'password'
        '.*phs[\d]{6}.*', # phsids
    ]]
)

def run():
    check_files()
 
def check_code_diff(filename):
    '''
    Check possible credentials for all newly added code lines
    '''
    added_code = Popen(["git", "diff", "--cached", "--", filename], stdout=PIPE)
    has_credential = False
    for code in added_code.stdout.readlines():
        try:
            code = code.decode()
        except UnicodeDecodeError:
            pass
        code = code.strip()
        if code.startswith('+'):
            if any(regex.match(code) for regex in SUSPICIOUS_CREDENTIALS):
                print(
                    'Found possible credentials on line: {blue}{line}{end} for file {blue}{file}{end}'
                    .format(line=code, file=filename, blue=bcolors.OKBLUE, end=bcolors.ENDC))
                has_credential = True
    return has_credential 

def check_files():
    '''
    Check all filenames if they have suspicious format
    '''
    has_credential = False
    filenames = Popen(["git", "diff", "--cached", "--name-only"], stdout=PIPE)
    for name in filenames.stdout.readlines():
        name = name.decode()
        name = name.strip()
        if name.endswith(SUSPICIOUS_FILENAME_EXTENSIONS)\
                or any(keyword in name for keyword in SUSPICIOUS_FILENAME_KEYWORDS):
            print('filename {blue}{file}{end} has suspicious format'
                  .format(blue=bcolors.OKBLUE, end=bcolors.ENDC, file=name))
            has_credential = True
        if check_code_diff(name):
            has_credential = True
    if has_credential:
        re_edit = raw_input('Found possible credentials.  Press y to ignore and n to cancel the commit. [y/N]: ')
        if re_edit.lower() in ['y', 'yes']:
            exit(0)
        exit(1)


run()
